title: ZBT Link
description: ZBT 开源固件发布平台
url: "https://open.zbtlink.com"
baseurl: ""
lang: zh-CN
timezone: Asia/Shanghai
github_username: zbtlink

markdown: kramdown
kramdown:
  input: GFM
permalink: pretty

collections:
  devices:
    output: true
    permalink: /devices/:name/

defaults:
  - scope:
      path: ""
      type: "devices"
    values:
      layout: device
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - README.md
  - .sass-cache
  - .jekyll-cache
