title: ZBT Link
description: Open firmware for ZBT network devices
url: "https://open.zbtlink.com"
baseurl: ""
lang: en
timezone: Asia/Shanghai
github_username: zbtlink

markdown: kramdown
kramdown:
  input: GFM
permalink: pretty

collections:
  devices:
    output: true
    permalink: /devices/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: default
      lang: en
  - scope:
      path: "zh"
    values:
      lang: zh
  - scope:
      path: ""
      type: "devices"
    values:
      layout: device
      lang: en
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      lang: en

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - README.md
  - .sass-cache
  - .jekyll-cache
  - admin
  - _config.local.yml
  - serve.ps1
  - serve.bat
